name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform-apply:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: infrastructure

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository at triggering commit
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{secrets.aws_role_terraform_particle41}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform
          format: lovely

      - name: Terraform Plan (gating check)
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan