name: Terraform Plan

on:
  pull_request:
    paths:
      - "infrastructure/**"
      - ".github/workflows/terraform-plan.yml"
      - ".github/workflows/terraform-apply.yml"
  push:
    branches: [main]
    paths:
      - "infrastructure/**"
      - ".github/workflows/terraform-plan.yml"
      - ".github/workflows/terraform-apply.yml"
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    defaults:
      run:
        working-directory: infrastructure

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{secrets.aws_role_terraform_particle41}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: trivy scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: trivy.txt
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi


      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform plan artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: terraform/tfplan
          retention-days: 1